apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-alert-manager
spec:
  replicas: {{ int .Values.alertmanager.replicaCount }}
  serviceName: {{ .Release.Name }}-alert-manager
  selector:
    matchLabels:
      app: {{ .Release.Name }}-alert-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-alert-manager
    spec:
      containers:
        - env:
          - name: DB_HOST
            value: {{ .Values.postgresql.nameConnect }}
          - name: DB_USERNAME
            value: {{ .Values.postgresql.auth.username }}
          - name: DB_PASSWORD
            value: {{ .Values.postgresql.auth.password }}
          - name: DB_DATABASE
            value: {{ .Values.postgresql.auth.database }}
          image: {{ .Values.image.repository }}/alert-manager:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}-alert-manager
          {{- with .Values.alertmanager.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/.env
              subPath: alert-manager.env
              readOnly: false
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/public/templates/templates.json
              subPath: alert-manager-templates.json
              readOnly: false
      hostname: {{ .Release.Name }}-alert-manager
      volumes:
        - name: {{ .Release.Name }}-configs
          configMap:
            name: {{ .Release.Name }}-configs
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secrets