apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configs
data:
  web-api.env: |-
{{ .Files.Get "configs/web-api.env" | indent 4}}
  synchronizer.env: |-
{{ .Files.Get "configs/synchronizer.env" | indent 4}}
  listener.env: |-
{{ .Files.Get "configs/listener.env" | indent 4}}
  cleaner.env: |-
{{ .Files.Get "configs/cleaner.env" | indent 4}}
  downloader.env: |-
{{ .Files.Get "configs/downloader.env" | indent 4}}