apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configs
data:
  web-api.env: |-
{{ .Files.Get "configs/web-api.env" | indent 4}}
  synchronizer.env: |-
{{ .Files.Get "configs/synchronizer.env" | indent 4}}
  listener.env: |-
{{ .Files.Get "configs/listener.env" | indent 4}}
  cleaner.env: |-
{{ .Files.Get "configs/cleaner.env" | indent 4}}
  downloader.env: |-
{{ .Files.Get "configs/downloader.env" | indent 4}}
  klines-listener.env: |-
{{ .Files.Get "configs/klines-listener.env" | indent 4}}
  klines-writer.env: |-
{{ .Files.Get "configs/klines-writer.env" | indent 4}}
  alert-manager.env: |-
{{ .Files.Get "configs/alert-manager.env" | indent 4}}
  alert-manager-templates.json: |-
{{ .Files.Get "configs/alert-manager-templates.json" | indent 4}}