apiVersion: batch/v1
kind: Job
metadata:
  name: downloader-coinbase-job
  labels:
    app: downloader-coinbase-job
  annotations:
    #"helm.sh/hook": post-install,post-upgrade
    #"helm.sh/hook-weight": "997"
    #"helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - env:
          - name: DB_HOST
            value: {{ .Values.postgresql.nameConnect }}
          - name: DB_USERNAME
            value: {{ .Values.postgresql.auth.username }}
          - name: DB_PASSWORD
            value: {{ .Values.postgresql.auth.password }}
          - name: DB_DATABASE
            value: {{ .Values.postgresql.auth.database }}
          - name: EXCHANGE
            value: coinbase
          - name: MRKT_TYPE
            value: spot
          - name: TIMEFRAMES
            value: 1d,1w,1M
          - name: RPM
            value: '100'
          image: {{ .Values.image.repository }}/downloader:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}-downloader-coinbase-spot-dwm
          {{- with .Values.downloadercoinbase.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/.env
              subPath: downloader.env
              readOnly: false
        - env:
          - name: DB_HOST
            value: {{ .Values.postgresql.nameConnect }}
          - name: DB_USERNAME
            value: {{ .Values.postgresql.auth.username }}
          - name: DB_PASSWORD
            value: {{ .Values.postgresql.auth.password }}
          - name: DB_DATABASE
            value: {{ .Values.postgresql.auth.database }}
          - name: EXCHANGE
            value: coinbase
          - name: MRKT_TYPE
            value: spot
          - name: TIMEFRAMES
            value: 1h
          - name: RPM
            value: '100'
          image: {{ .Values.image.repository }}/downloader:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}-downloader-coinbase-spot-h
          {{- with .Values.downloadercoinbase.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/.env
              subPath: downloader.env
              readOnly: false
        - env:
          - name: DB_HOST
            value: {{ .Values.postgresql.nameConnect }}
          - name: DB_USERNAME
            value: {{ .Values.postgresql.auth.username }}
          - name: DB_PASSWORD
            value: {{ .Values.postgresql.auth.password }}
          - name: DB_DATABASE
            value: {{ .Values.postgresql.auth.database }}
          - name: EXCHANGE
            value: coinbase
          - name: MRKT_TYPE
            value: spot
          - name: TIMEFRAMES
            value: 1m,5m,15m
          - name: RPM
            value: '100'
          image: {{ .Values.image.repository }}/downloader:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}-downloader-coinbase-spot-m
          {{- with .Values.downloadercoinbase.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/.env
              subPath: downloader.env
              readOnly: false
      hostname: {{ .Release.Name }}-downloader-coinbase
      volumes:
        - name: {{ .Release.Name }}-configs
          configMap:
            name: {{ .Release.Name }}-configs
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secrets