apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
spec:
  selector:
    app: {{ .Release.Name }}-front
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
status:
  loadBalancer: {}