apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: front
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: web-api
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
status:
  loadBalancer: {}