apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-api
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ int .Values.webapi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web-api
    spec:
      containers:
        - env:
          - name: DB_HOST
            value: {{ .Release.Name }}-{{ .Values.mysql.nameOverride }}
          - name: DB_USERNAME
            value: {{ .Release.Name }}-{{ .Values.postgresql.auth.username }}
          - name: DB_PASSWORD
            value: {{ .Release.Name }}-{{ .Values.postgresql.auth.password }}
          - name: DB_DATABASE
            value: {{ .Release.Name }}-{{ .Values.postgresql.auth.database }}
          image: {{ .Values.image.repository }}/web-api:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: web-api
          ports:
            - containerPort: 7020
          {{- with .Values.webapi.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/.env
              subPath: web-api.env
              readOnly: false
      hostname: web-api
      volumes:
        - name: {{ .Release.Name }}-configs
          configMap:
            name: {{ .Release.Name }}-configs
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secrets