apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-api
spec:
  selector:
    app: {{ .Release.Name }}-web-api
  ports:
    - name: web-api
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
status:
  loadBalancer: {}