image:

  repository: cryptotradinglabrg.azurecr.io
  tag: latest
  pullPolicy: Always

services:
  targetPort: 3000

front:
  resources: {}

webapi:
  hpa:
    enabled: true
    cputhreshold: 50
    minpods: 1
    maxpods: 2
  replicaCount: 1
  resources: {}

synchronizer:
  replicaCount: 1
  resources: {}

listenerbinance:
  replicaCount: 1
  resources: {}

listenerbus:
  replicaCount: 1
  resources: {}

listenercoinbase:
  replicaCount: 1
  resources: {}

listenerokx:
  replicaCount: 1
  resources: {}

cleanerbinance:
  replicaCount: 1
  resources: {}

cleanerbus:
  replicaCount: 1
  resources: {}

cleanercoinbase:
  replicaCount: 1
  resources: {}

cleanerokx:
  replicaCount: 1
  resources: {}

downloaderbinance:
  replicaCount: 1
  resources: {}

downloaderbus:
  replicaCount: 1
  resources: {}

downloadercoinbase:
  replicaCount: 1
  resources: {}

downloaderokx:
  replicaCount: 1
  resources: {}

postgresql:
  nameOverride: colombo.private.postgres.database.azure.com
  auth:
    username: digger
    password: BshfRyeIeA9gqSo
    database: trading
  initdb:
    scripts:
      createdb.sql: |-
        CREATE DATABASE "trading";