image:
  repository: ghcr.io/solution8
  tag: latest
  pullPolicy: Always

services:
  targetPort: 3000

front:
  resources: {}

webapi:
  hpa:
    enabled: true
    cputhreshold: 50
    minpods: 1
    maxpods: 2
  replicaCount: 1
  resources: {}

synchronizer:
  replicaCount: 1
  resources: {}

postgresql:
  nameOverride: postgresql
  auth:
    username: admin
    password: admin
    database: trading
  initdb:
    scripts:
      createdb.sql: |-
        CREATE DATABASE "trading";