image:

  #repository: cryptotradinglabrg.azurecr.io
  repository: ghcr.io/solution8
  tag: latest
  pullPolicy: Always

services:
  targetPort: 3000

front:
  resources: {}

webapi:
  hpa:
    enabled: true
    cputhreshold: 50
    minpods: 1
    maxpods: 2
  replicaCount: 1
  resources: {}

synchronizer:
  replicaCount: 1
  resources: {}

klineslistenerbinance:
  replicaCount: 1
  resources: {}

klineslistenerbus:
  replicaCount: 1
  resources: {}

klineslistenercoinbase:
  replicaCount: 1
  resources: {}

klineslistenerokx:
  replicaCount: 1
  resources: {}

klineswriterbinance:
  replicaCount: 1
  resources: {}

klineswriterbus:
  replicaCount: 1
  resources: {}

klineswritercoinbase:
  replicaCount: 1
  resources: {}

klineswriterokx:
  replicaCount: 1
  resources: {}

cleanerbinance:
  replicaCount: 1
  resources: {}

cleanerbus:
  replicaCount: 1
  resources: {}

cleanercoinbase:
  replicaCount: 1
  resources: {}

cleanerokx:
  replicaCount: 1
  resources: {}

downloaderbinance:
  replicaCount: 1
  resources: {}

downloaderbus:
  replicaCount: 1
  resources: {}

downloadercoinbase:
  replicaCount: 1
  resources: {}

downloaderokx:
  replicaCount: 1
  resources: {}

alertmanager:
  replicaCount: 1
  resources: {}

#PROD
#postgresql:
#  nameOverride: colombo.postgres.database.azure.com
#  auth:
#    username: digger
#    password: OLK5CbMyXRRnbui
#    database: trading
#  initdb:
#    scripts:
#      createdb.sql: |-
#        CREATE DATABASE "trading";

#DEV
postgresql:
  nameOverride: postgresql
  nameConnect: screener-postgresql
  auth:
    username: admin
    password: admin
    database: trading
  initdb:
    scripts:
      createdb.sql: |-
        CREATE DATABASE "trading";

rabbitmq:
  nameOverride: rabbitmq
  auth:
    username: admin
    existingPasswordSecret: screener-secrets